name: neutcurve
channels:
  - bioconda
  - r
  - conda-forge
  - defaults
  - schrodinger
dependencies:
  - jupyterlab
  - mamba
  - nbdime
  - nodejs
  - pandas==1.5.1
  - pip
  - python
  - pip:
    - scipy==1.10.1
    - numpy==1.23.4
    - neutcurve==0.5.7
    - matplotlib==3.6.3
    - seaborn==0.12.2
    - ete3==3.1.2
    - Bio
    - pymsaviz==0.4.0